#!/usr/bin/env python

# ruff: noqa: E501

frequencies = {
    '1': 'Traveler',
    '2': 'Quantum',
    '3': 'EscapePod',
    '4': 'WarpCore',
    '5': 'HideAndSeek',
    '6': 'Radio',
}

signals = {
    '10': 'Traveler_Esker',
    '11': 'Traveler_Chert',
    '12': 'Traveler_Riebeck',
    '13': 'Traveler_Gabbro',
    '14': 'Traveler_Feldspar',
    '15': 'Traveler_Nomai',
    '16': 'Traveler_Prisoner',
    '20': 'Quantum_CT_Shard',
    '21': 'Quantum_TH_MuseumShard',
    '22': 'Quantum_TH_GroveShard',
    '23': 'Quantum_BH_Shard',
    '24': 'Quantum_GD_Shard',
    '25': 'Quantum_QM',
    '30': 'EscapePod_CT',
    '31': 'EscapePod_BH',
    '32': 'EscapePod_DB',
    '40': 'WhiteHole_WH',
    '41': 'WhiteHole_SS_Receiver',
    '42': 'WhiteHole_CT_Receiver',
    '43': 'WhiteHole_CT_Experiment',
    '44': 'WhiteHole_TT_Receiver',
    '45': 'WhiteHole_TT_TimeLoopCore',
    '46': 'WhiteHole_TH_Receiver',
    '47': 'WhiteHole_BH_NorthPoleReceiver',
    '48': 'WhiteHole_BH_ForgeReceiver',
    '49': 'WhiteHole_GD_Receiver',
    '60': 'HideAndSeek_Galena',
    '61': 'HideAndSeek_Tephra',
    '62': 'HideAndSeek_Arkose',
    '100': 'RadioTower',
    '101': 'MapSatellite',
}

rumors = {
    'BH_RIEBECK_R1': 'Riebeck headed to Brittle Hollow to investigate something the Nomai were doing at the south pole.',
    'BH_RIEBECK_R2': 'Riebeck landed their ship near the big dome at the south pole. The door leading inside was broken, so they decided to head north to the ruins on the equator in search of a way beneath the surface.',
    'BH_RIEBECK_R3': 'Riebeck discovered an old Nomai path near their campsite on the equator. The path starts inside the ruined building with trees growing out of it.',
    'BH_RIEBECK_R4': 'Riebeck reached the Crossroads and continued downward in search of oxygen.',
    'BH_QUANTUM_RESEARCH_TOWER_R1': "This tower (located on Brittle Hollow's equator) held useful knowledge for Nomai embarking on their first pilgrimage to the Quantum Moon.",
    'BH_QUANTUM_RESEARCH_TOWER_R2': "A Nomai named Solanum was told to visit the Tower of Quantum Knowledge (on Brittle Hollow's equator) to learn one final rule before embarking on her pilgrimage to the Quantum Moon.",
    'BH_QUANTUM_SHARD_R1': 'The Nomai noticed a strange rock shard that appeared to wander when no one was watching.',
    'BH_ESCAPE_POD_R1': 'One of the three Nomai escape pods landed somewhere on Brittle Hollow.',
    'BH_OLD_SETTLEMENT_R1': 'The Nomai survivors who crashed on Brittle Hollow climbed down the cliff to a shelter site below the surface.',
    'BH_HANGING_CITY_R1': 'The Nomai decided to migrate from the Old Settlement to the northern glacier. They used gravity crystals to craft a stable path beneath the surface.',
    'BH_HANGING_CITY_R2': "There's a huge Nomai city just to the north of Riebeck's campsite.",
    'BH_BLACK_HOLE_FORGE_R1': 'The Black Hole Forge is suspended below the Hanging City. I found a switch in the Meltwater District that raises and lowers the forge.',
    'BH_BLACK_HOLE_FORGE_R2': 'The Black Hole Forge District is the highest district in the Hanging City.',
    'BH_BLACK_HOLE_FORGE_R3': 'A Nomai named Poke planned to create a new advanced warp core in the Black Hole Forge.',
    'BH_BLACK_HOLE_FORGE_R4': 'The Nomai crafted warp cores at the Black Hole Forge before delivering them to Ash Twin.',
    'BH_OBSERVATORY_R1': "The Nomai decided to build a larger, more sophisticated Eye signal locator on Brittle Hollow's south pole.",
    'BH_OBSERVATORY_R2': "There are two paths beneath Brittle Hollow's surface that lead to the observatory. One starts at the gravity cannon, and the other starts at the Tower of Quantum Knowledge.",
    'BH_OBSERVATORY_R3': "Riebeck says you can't get into the observatory from the surface (they tried), but there's probably a path to it beneath the crust somewhere.",
    'BH_OBSERVATORY_R4': "There's a door to the observatory on the surface, but it's broken.",
    'BH_TORNADO_SIMULATION_R1': "The Nomai at the Southern Observatory constructed a model of Giant's Deep that revealed how an object might sink below the strong ocean current.",
    'BH_RIEBECK_X1': 'Riebeck has set up camp at the bottom of the Crossroads. Their excitement at being surrounded by so much Nomai history is matched only by their terror of the black hole.',
    'BH_RIEBECK_X2': "Riebeck is Timber Hearth's only archaeologist. They overcame their fear of space to explore Brittle Hollow's treasure trove of Nomai culture.",
    'BH_GRAVITY_CANNON_X1': 'A huge cylindrical structure that generates a strong upward gravity field.',
    'BH_GRAVITY_CANNON_X2': 'I recalled a Nomai shuttle from the Quantum Moon.',
    'BH_QUANTUM_RESEARCH_TOWER_X1': 'The Nomai built a shrine on the Quantum Moon to aid in the pilgrimage to its sixth location. "Remember this final rule: To explore the sixth location, the shrine must be on the moon\u2019s north pole."',
    'BH_QUANTUM_RESEARCH_TOWER_X2': 'The pilgrimage to the Quantum Moon was a deeply significant journey for the Nomai.',
    'BH_QUANTUM_RESEARCH_TOWER_X3': 'After the two groups of Nomai stranded on Ember Twin and Brittle Hollow were reunited, it became their united goal to find and visit the Quantum Moon.',
    'BH_QUANTUM_SHARD_X1': 'A strange rock shard that wanders when no one is watching. The Nomai determined this shard is the reason objects in this grove behave in a quantum manner.',
    'BH_QUANTUM_SHARD_X2': 'The Nomai hypothesized that this shard is actually a piece of the Quantum Moon.',
    'BH_QUANTUM_SHARD_X3': 'This shard emits the same signal as the Quantum Moon.',
    'BH_WARP_RECEIVER_X1': 'The north pole of Brittle Hollow is covered in snow and ice. There is a uniquely shaped Nomai ruin on the surface.',
    'BH_WARP_RECEIVER_X2': 'The Nomai were able to warp here from the White Hole Station. This is where they first recreated warp technology.',
    'BH_ESCAPE_POD_X1': 'One of three Nomai escape pods that crashed in our solar system.',
    'BH_ESCAPE_POD_X2': 'All three escape pods were launched from something called the Vessel, which was badly damaged.',
    'BH_OLD_SETTLEMENT_X1': 'The Nomai constructed a temporary settlement beneath their crashed escape pod.',
    'BH_OLD_SETTLEMENT_X2': 'The Nomai worked together to recall an eye-shaped signal they encountered while aboard the Vessel.',
    'BH_OLD_SETTLEMENT_X3': 'The signal was somehow older than the universe itself. The Nomai decided to call it the "Eye of the universe."',
    'BH_OLD_SETTLEMENT_X4': 'The Nomai abandoned this settlement over growing concerns about its stability.',
    'BH_MURAL_3_X1': 'A mural of three escape pods evacuating the Nomai vessel.',
    'BH_MURAL_2_X1': 'A mural of Dark Bramble ensnaring the Nomai vessel.',
    'BH_MURAL_1_X1': 'A mural of a Nomai vessel encountering a signal.',
    'BH_HANGING_CITY_X1': "A Nomai city suspended beneath Brittle Hollow's northern glacier. The city is divided vertically into four districts.",
    'BH_HANGING_CITY_X2': 'I found a switch in the Meltwater District that raises and lowers the Black Hole Forge.',
    'BH_HANGING_CITY_X3': 'The Nomai debated how to obtain the powerful, highly advanced warp core required for the Ash Twin Project.',
    'BH_HANGING_CITY_X4': 'The Nomai traveled to this solar system in pursuit of a signal from something older than the universe itself. They named the source of this signal the "Eye of the universe."',
    'BH_BLACK_HOLE_FORGE_X4': "A warp tower's alignment point is not its warp receiver. Rather, a warp tower always aligns with the center of its corresponding astral body.",
    'BH_BLACK_HOLE_FORGE_X5': 'The warp receiver must be located on (or in close orbit around) the relevant astral body.',
    'BH_BLACK_HOLE_FORGE_X6': 'The Hourglass Twins are so close together they function as a single astral body, with a shared alignment point in between them.',
    'BH_BLACK_HOLE_FORGE_X1': 'All of the warp towers were being constructed on Ash Twin, while the six warp receivers were being constructed at different locations.',
    'BH_BLACK_HOLE_FORGE_X3': 'A Nomai named Poke successfully forged an advanced warp core for the Ash Twin Project.',
    'BH_WARP_ALIGNMENT_MAP_X1': 'A diagram depicting the alignment angle between a warp tower and its corresponding astral body.',
    'BH_WARP_ALIGNMENT_MAP_X2': "Warp tower alignment angles are not exact. They only need to be within five degrees of the astral body's center.",
    'BH_WARP_ALIGNMENT_MAP_X3': 'This results in slightly longer warp windows that last roughly several seconds.',
    'BH_WARP_ALIGNMENT_MAP_X4': 'Anyone stepping onto the warp platform during the active window will be immediately warped.',
    'BH_OBSERVATORY_X1': "The new, more sensitive locator the Nomai built in this observatory was unable to detect any trace of the Eye's signal.",
    'BH_OBSERVATORY_X2': 'Based on their knowledge of the Quantum Moon, the Nomai believed the Eye was in a distant orbit around the sun.',
    'BH_OBSERVATORY_X3': "The Nomai decided to stop searching for the Eye's signal and instead look for it visually by sending out a deep space probe.",
    'BH_OBSERVATORY_X4': 'There were concerns that the probability of launching a probe in the correct direction would be absurdly small.',
    'BH_TORNADO_SIMULATION_X1': "Most cyclones on Giant's Deep rotate clockwise. These are the cyclones the Nomai used to send components into orbit.",
    'BH_TORNADO_SIMULATION_X2': 'There also exists a rarer type of cyclone that spins the opposite direction and pushes objects beneath the waters and below the current.',
    'VM_VOLCANO_X1': 'Ore samples from the Nomai Mines on Timber Hearth were sent to this volcano for durability testing.',
    'VM_VOLCANO_X2': 'The Nomai were trying to craft a (briefly) supernova-proof shell to encase the Ash Twin Project.',
    'VM_VOLCANO_X3': 'Even the smallest crack or opening in the protective shell would destroy everything.',
    'WHS_R1': "There is a White Hole Station on the other side of Brittle Hollow's black hole.",
    'WHS_R2': 'Several Nomai returned to the station to investigate an equipment reading that appeared to violate causality.',
    'WHS_R3': 'The experiments at the High Energy Lab were based on extraordinary findings from the White Hole Station.',
    'WHS_R4': 'The towers on Ash Twin were modeled after the White Hole Station.',
    'WHS_X4': 'Every Nomai warp tower is tuned to a specific astral body.',
    'WHS_X1': "To use a tower, you must be standing on the warp platform during the tower's alignment with its corresponding astral body (the alignment happens when the astral body is directly overhead).",
    'WHS_X2': 'The Nomai noticed something strange: Warped objects appeared to arrive at the receiver on Brittle Hollow slightly before they departed the White Hole Station.',
    'WHS_X3': 'This negative time interval between an object arriving and departing was incredibly miniscule (roughly one hundred-thousandth of a second). The Nomai were skeptical if their equipment could even measure time to such a small degree.',
    'DB_FELDSPAR_R1': "Feldspar headed off to Dark Bramble after reaching the core of Giant's Deep.",
    'DB_FELDSPAR_R2': 'When I launch my scout into the seed that crashed on Timber Hearth, it ends up in a much bigger space filled with fog and thorny vines.',
    'DB_FROZEN_JELLYFISH_R1': "Feldspar hinted that a secret to reaching the core of Giant's Deep lies at the end of the hollow vine they crashed their ship into. To find Feldspar's ship, I'll want to go to the tail end of the anglerfish skeleton and look for a flickering light in the fog.",
    'DB_ESCAPE_POD_R1': 'One of the three Nomai escape pods never made it out of Dark Bramble.',
    'DB_NOMAI_GRAVE_R1': 'The survivors from Escape Pod 3 abandoned the wreckage and attempted to return to the Vessel.',
    'DB_NOMAI_GRAVE_R2': 'The survivors decided to follow the closer of the two Vessel beacons due to their limited air supply. They planned to leave a trail of lights behind them in case someone heard their distress signal.',
    'DB_VESSEL_R1': 'The Nomai warped to this solar system in a spaceship called the Vessel. They were attempting to follow a signal from the Eye of the universe.',
    'DB_VESSEL_R2': 'The Vessel crashed somewhere in Dark Bramble.',
    'DB_VESSEL_R3': "The Vessel's warp core broke when the ship crashed in Dark Bramble.",
    'DB_VESSEL_R4': 'I launched my scout into the seed at the Nomai Grave and took photos of an enormous derelict Nomai ship.',
    'DB_FELDSPAR_X1': 'Feldspar is alive! They crashed their ship and is now camping inside a huge anglerfish skeleton.',
    'DB_FELDSPAR_X2': "Feldspar doesn't think my scout tracker is wrong when it says my scout is in two places at once. They have a theory that space doesn\u2019t work the same inside Dark Bramble.",
    'DB_FELDSPAR_X3': "Feldspar doesn't sound overly eager to return to civilization. They've been enjoying the (relative) peace and quiet.",
    'DB_FROZEN_JELLYFISH_X1': 'Feldspar documented their attempts to eat this enormous jellyfish frozen in the ice. The outside was all rubbery and tough, possibly because it insulates the jellyfish\u2019s insides from getting zapped by electricity.',
    'DB_FROZEN_JELLYFISH_X2': 'Feldspar decided to venture into the jellyfish\u2019s interior cavity to see if it tasted any better on the inside.',
    'DB_FROZEN_JELLYFISH_X3': 'After tasting the inside of the jellyfish, Feldspar concluded that these jellyfish are only useful for insulation from electricity.',
    'DB_ESCAPE_POD_X1': 'One of three Nomai escape pods that crashed in our solar system.',
    'DB_ESCAPE_POD_X2': 'All three escape pods were launched from something called the Vessel, which was badly damaged.',
    'DB_ESCAPE_POD_X3': 'The survivors from Escape Pod 3 detected two distinct beacons from the Vessel, as if it was in two locations at once.',
    'DB_NOMAI_GRAVE_X1': 'The survivors from Escape Pod 3 followed one of the two Vessel beacons to a small Dark Bramble seed, where they could go no further.',
    'DB_NOMAI_GRAVE_X2': "The Nomai could faintly hear the Vessel's beacon from within the seed, but the opening was too small for a single Nomai to fit through, much less an escape pod.",
    'DB_NOMAI_GRAVE_X3': "The Vessel's beacon was dying, and would soon be gone completely.",
    'DB_NOMAI_GRAVE_X4': 'If I launch my scout into the seed, I can take photos of an enormous derelict Nomai ship.',
    'DB_VESSEL_X1': 'I found the derelict Nomai Vessel deep within Dark Bramble.',
    'DB_VESSEL_X2': "The Vessel's warp core is long dead.",
    'DB_VESSEL_X3': "I activated a three-sided pillar on the Vessel's bridge that appears to be some sort of input device.",
    'DB_VESSEL_X4': "The Nomai tried to call for help, but the Vessel's outgoing message system broke during the crash.",
    'DB_VESSEL_X5': 'The Vessel can still hear incoming messages from other Nomai vessels. The remaining Nomai clans are regrouping in response to the impending death of the universe.',
    'DB_VESSEL_X6': 'I found a recording of the original signal the Nomai encountered from the Eye of the universe. The Nomai were worried the signal might disappear, so they warped before they could tell another clan where they were going.',
    'ORBITAL_PROBE_CANNON_R1': 'The Nomai finished building the final module for the Orbital Probe Cannon and sent it into orbit around Giant\u2019s Deep.',
    'ORBITAL_PROBE_CANNON_R2': "I used a Nomai projection pool and saw the interior of a space station in orbit around Giant's Deep.",
    'ORBITAL_PROBE_CANNON_R4': 'The Nomai decided to construct a probe cannon in orbit around Giant\u2019s Deep.',
    'ORBITAL_PROBE_CANNON_R3': 'Gabbro sees a bright flash in the sky at the start of every loop. Something must be happening in orbit around Giant\u2019s Deep.',
    'OPC_SUNKEN_MODULE_R1': 'One of the Orbital Probe Cannon\u2019s three modules.',
    'OPC_SUNKEN_MODULE_R5': 'The Probe Tracking Module is receiving data from the launched probe.',
    'OPC_SUNKEN_MODULE_R4': 'Any Nomai aboard the Probe Tracking Module would be the first to see the coordinates of the Eye of the universe.',
    'OPC_SUNKEN_MODULE_R2': 'A Nomai computer reports the Probe Tracking Module as "missing."',
    'OPC_SUNKEN_MODULE_R3': 'I saw the Probe Tracking Module through a Nomai projection pool. It looks like the module is underwater. I could see purple electricity outside the viewport.',
    'OPC_BROKEN_MODULE_R1': 'One of the Orbital Probe Cannon\u2019s three modules.',
    'OPC_BROKEN_MODULE_R2': 'The Launch Module looks heavily damaged. There\u2019s a huge breach in the glass viewport.',
    'OPC_BROKEN_MODULE_R3': "The Launch Module's viewport window is fractured, exposing it to the vacuum of space.",
    'OPC_INTACT_MODULE_R1': 'One of the Orbital Probe Cannon\u2019s three modules.',
    'ORBITAL_PROBE_CANNON_X1': "The broken remains of a Nomai space station in orbit around Giant's Deep. There are three accessways branching off from the central hub area.",
    'ORBITAL_PROBE_CANNON_X2': 'The Orbital Probe Cannon was created to find the precise location of the Eye of the universe.',
    'ORBITAL_PROBE_CANNON_X3': 'The Nomai pushed the Orbital Probe Cannon above its maximum power setting to create the greatest chance of finding the Eye of the universe.',
    'OPC_SUNKEN_MODULE_X1': 'The Orbital Probe Cannon has launched millions of probes.',
    'OPC_SUNKEN_MODULE_X2': 'The 9,318,054th probe located a deep space anomaly matching all known criteria for the Eye of the universe.',
    'OPC_SUNKEN_MODULE_X3': "The statue in the Probe Tracking Module automatically records each probe's trajectory and transmits the data to the Ash Twin Project.",
    'OPC_EYE_COORDINATES_X1': 'I found Nomai coordinates marking the location of the Eye of the universe.',
    'OPC_BROKEN_MODULE_X1': 'The Launch Module is badly damaged, but its projection pool is still intact.',
    'OPC_BROKEN_MODULE_X2': "A Nomai named Mallow argued that it wouldn't matter if the cannon's structural integrity was compromised, since they only needed to fire the probe once.",
    'OPC_BROKEN_MODULE_X3': "A Nomai named Privet countered that they wouldn't be capable of receiving the probe's data if the Probe Tracking Module was destroyed.",
    'OPC_INTACT_MODULE_X1': 'The Control Module (recently) received a request from the Ash Twin Project to launch the probe. The cannon was aligned with a randomly selected probe trajectory.',
    'OPC_INTACT_MODULE_X2': "The probe was successfully launched, but the cannon's structural integrity was compromised in the process. Damage is detected in multiple modules.",
    'TH_ZERO_G_CAVE_R1': 'I hear Gossan has the zero-g cave set up if I want a refresher before I launch.',
    'TH_IMPACT_CRATER_R1': "Esker's signalscope log reports harmonica music coming from somewhere on Timber Hearth. They claim it sounds just like Feldspar's harmonica, but Feldspar disappeared in space ages ago.",
    'TH_NOMAI_MINE_R1': 'The Nomai were mining ore somewhere on Timber Hearth.',
    'TH_QUANTUM_SHARD_R1': "Chert detected a strange signal coming from the crater at Timber Hearth's south pole. It's very similar to the signal emitted by the Quantum Moon.",
    'TH_QUANTUM_SHARD_R2': 'The Nomai detected a quantum signal coming from somewhere on Timber Hearth.',
    'TH_VILLAGE_X1': 'The one and only Hearthian village, as well as the main source of explosions on this planet.',
    'TH_VILLAGE_X2': 'The Nomai statue in the observatory opened its eyes and looked at me! I saw strange glowing lights and my own memories flashed before my eyes.',
    'TH_VILLAGE_X3': "Hal says the statue has never opened its eyes before (despite Hornfels' best efforts).",
    'TH_ZERO_G_CAVE_X1': 'A cave at the very center of Timber Hearth used by Outer Wilds Ventures to train new astronauts.',
    'TH_ZERO_G_CAVE_X2': 'I successfully repaired another "satellite" for Gossan.',
    'TH_IMPACT_CRATER_X1': "A seed from Dark Bramble crashed here and has already taken root. Tektite wants to use a scout launcher to get a look at what's inside.",
    'TH_IMPACT_CRATER_X2': 'My signalscope picks up harmonica music when I aim it at the seed.',
    'TH_IMPACT_CRATER_X3': 'I launched my Little Scout into the seed. Somehow the seed is much bigger on the inside.',
    'TH_NOMAI_MINE_X1': 'The Nomai mined ore from this site to craft a protective shell designed to physically seal off the central chamber inside Ash Twin.',
    'TH_NOMAI_MINE_X2': 'Once the shell was finished, the Nomai checked to ensure there were no longer any physical entrances or cracks.',
    'TH_NOMAI_MINE_X3': 'The Nomai discovered a species of four-eyed, semi-aquatic lifeforms in the waterways near the mine.',
    'TH_QUANTUM_SHARD_X1': 'There is a strange rock shard in this grove that moves when I\u2019m not watching. It emits a signal on the Quantum Fluctuations frequency.',
    'TH_QUANTUM_SHARD_X2': 'I found a poem written on one of the trees in the grove.',
    'TH_RADIO_TOWER_X1': 'A radio tower designed to receive photos taken by the deep space satellite. There are several photos of the entire solar system hanging on the walls. Hornfels noticed something strange in one of the photos, but concluded equipment malfunction was the only sensible explanation.',
    'CT_GRAVITY_CANNON_R1': "The Nomai shuttle that's frozen on the Interloper can be called home to the gravity cannon on Ember Twin.",
    'CT_ESCAPE_POD_R1': 'One of the three Nomai escape pods landed somewhere on the Hourglass Twins.',
    'CT_ESCAPE_POD_R2': "Chert saw a Nomai shipwreck shooting a beam of light into the sky somewhere on Ember Twin's southern hemisphere.",
    'CT_HIGH_ENERGY_LAB_R1': 'The negative time interval measured at the White Hole Station was further investigated at the High Energy Lab (in the canyon at Ember Twin\u2019s equator).',
    'CT_HIGH_ENERGY_LAB_R2': 'The Ash Twin Project was planned at the High Energy Lab, a building with large solar panels on Ember Twin\u2019s equator.',
    'CT_HIGH_ENERGY_LAB_R3': 'The High Energy Lab can only be accessed by a path from the Sunless City.',
    'CT_WARP_TOWER_MAP_R1': "There are tower designs in the High Energy Lab that reveal each warp receiver's location.",
    'CT_SUNLESS_CITY_R1': 'The Nomai survivors who crashed on Ember Twin decided to seek shelter in the caves beneath their crashed escape pod.',
    'CT_SUNLESS_CITY_R3': 'The Nomai discovered a promising long-term shelter site at the end of one of the passages beneath the escape pod.',
    'CT_SUNLESS_CITY_R4': 'Chert thinks the lack of surface ruins means the Nomai must have lived somewhere underground.',
    'CT_SUNLESS_CITY_R5': 'There is a path leading to the High Energy Lab from the Sunless City.',
    'CT_SUNLESS_CITY_R2': 'I found a trailmarker for the the Sunless City, but the path is blocked.',
    'CT_ANGLERFISH_FOSSIL_R1': 'I found a cave with an anglerfish fossil inside, but the opening is only big enough for my scout.',
    'CT_ANGLERFISH_FOSSIL_R2': 'The Nomai learned how to evade anglerfish (theoretically, at least) by studying an anglerfish fossil they found on Ember Twin.',
    'CT_ANGLERFISH_FOSSIL_R3': 'Nomai children used to play a game in Fossil Fish Cave. There is a way to enter Fossil Fish Cave from Stepping Stone Cave.',
    'CT_ANGLERFISH_FOSSIL_R4': 'The entrance from Stepping Stone Cave is hard to see unless the anglerfish is fed a light first.',
    'CT_QUANTUM_CAVES_R1': 'The Nomai detected a quantum signal coming from somewhere on the Hourglass Twins.',
    'CT_LAKEBED_CAVERN_R1': 'The wandering rock was first spotted in a cave at the bottom of the dry lakebed at Ember Twin\u2019s north pole.',
    'CT_LAKEBED_CAVERN_R2': 'A Nomai named Coleus mysteriously vanished from a cave at the bottom of the dry lakebed at Ember Twin\u2019s north pole.',
    'CT_CHERT_X1': 'Chert has set up their astronomy gear on the north pole of Ember Twin.',
    'CT_CHERT_X2': 'Chert has spotted an unusually high number of supernovae recently.',
    'CT_CHERT_X3': 'All of the stars in the universe are dying, including our sun.',
    'CT_CHERT_X4': "The stars are simply dying from old age. Apparently they're much older than we realized.",
    'CT_CHERT_X5': "Chert has become catatonic in response to our sun's imminent death.",
    'CT_QUANTUM_MOON_LOCATOR_X1': "A Nomai device created to track the Quantum Moon's location.",
    'CT_QUANTUM_MOON_LOCATOR_X2': 'The Nomai hypothesized that the Quantum Moon might be a form of macroscopic quantum mechanics.',
    'CT_QUANTUM_MOON_LOCATOR_X3': "The Quantum Moon travels to at least five locations, but sometimes the locator can't tell where the moon is.",
    'CT_GRAVITY_CANNON_X1': 'A huge cylindrical structure that generates a strong upward gravity field.',
    'CT_GRAVITY_CANNON_X2': 'I recalled a Nomai shuttle from the Interloper.',
    'CT_ESCAPE_POD_X1': 'One of three Nomai escape pods that crashed in our solar system.',
    'CT_ESCAPE_POD_X2': 'All three escape pods were launched from something called the Vessel, which was badly damaged.',
    'CT_HIGH_ENERGY_LAB_X1': 'The Nomai successfully reproduced the temporal anomaly first observed at the White Hole Station (warped objects appear to arrive before they depart).',
    'CT_HIGH_ENERGY_LAB_X2': 'The Nomai discovered they could increase the negative time interval between arrival and departure by adding energy to the warp cores.',
    'CT_HIGH_ENERGY_LAB_X3': 'The Nomai wanted to know if a 22-minute negative time interval was possible. They concluded it would require new technology to produce the necessary energy as well an advanced warp core to handle those energies. Ash Twin was proposed as a location for the project.',
    'CT_WARP_TOWER_MAP_X1': "Designs for each of the towers on Ash Twin's equator.",
    'CT_WARP_TOWER_MAP_X4': 'Each tower warps to a different planet (although many Nomai were quick to note that the sun is not actually a planet).',
    'CT_WARP_TOWER_MAP_X3': 'Each tower was designed to visually reflect its warp destination.',
    'CT_WARP_TOWER_MAP_X2': 'The towers allowed the Nomai to quickly travel between Ash Twin and all other locations crucial to the Ash Twin Project.',
    'CT_SUNLESS_CITY_X1': 'A Nomai city built into the walls of a huge underground cavern. The city is divided vertically into four districts.',
    'CT_SUNLESS_CITY_X2': 'The Nomai debated building a Sun Station in order to power the Ash Twin Project. Several Nomai opposed its construction, arguing that failure could result in the destruction of the solar system.',
    'CT_SUNLESS_CITY_X3': 'The Nomai traveled to this solar system in pursuit of a signal from something older than the universe itself. They named the source of this signal the "Eye of the universe."',
    'CT_ANGLERFISH_FOSSIL_X1': 'Nomai children used to play a game here. One player was the anglerfish and wore a blindfold. The rest of the children (the littlefish) lined up against one wall. When the anglerfish said go, the littlefish had to sneak across to the other side.',
    'CT_ANGLERFISH_FOSSIL_X2': 'The blindfold rule was added because real anglerfish are blind.',
    'CT_ANGLERFISH_FOSSIL_X3': "The adult Nomai were delighted to see the children incorporate their research into the game's rules.",
    'CT_QUANTUM_CAVES_X1': 'The Nomai noticed a strange wandering rock that appeared in multiple caves on Ember Twin\u2019s northern hemisphere.',
    'CT_QUANTUM_CAVES_X2': 'I found a strange rock shard that moves when I\u2019m not watching. It emits a signal on the Quantum Fluctuations frequency.',
    'CT_LAKEBED_CAVERN_X1': "A Nomai named Coleus was standing on the wandering rock when another Nomai's lantern died. When they relit the lantern, Coleus and the rock were both gone.",
    'CT_LAKEBED_CAVERN_X2': 'To travel with a quantum object, I must stand on the object and cease to observe my surroundings (meaning I must be in complete darkness). Coleus used this quantum rule to escape the cave he was trapped in.',
    'CT_LAKEBED_CAVERN_X3': 'Coleus and Merolae returned to examine the rock. They theorized that when a conscious being is in contact with a quantum object and ceases to observe his or her surroundings, the being can become entangled with that quantum object, and they both move together.',
    'S_SUNSTATION_R1': 'There is a way to safely travel to the Sun Station from Ash Twin.',
    'S_SUNSTATION_R2': 'The Nomai debated building a Sun Station in order to power the Ash Twin Project.',
    'S_SUNSTATION_R3': 'The Nomai built something called the Sun Station, but not everyone supported its construction.',
    'S_SUNSTATION_X1': 'The Sun Station was designed to make the sun go supernova.',
    'S_SUNSTATION_X2': 'The Nomai fired the Sun Station but it had no effect on the sun. They concluded that the Sun Station could never cause the sun to go supernova.',
    'S_SUNSTATION_X3': 'After the failure of the Sun Station, the Nomai took a break to investigate the newly arrived comet.',
    'S_SUNSTATION_X4': 'According to a Nomai computer, our sun has reached the end of its natural life cycle.',
    'TM_ESKER_R1': 'Sounds like Esker is still stationed on the Attlerock. They\u2019ve been there by themself for a while.',
    'TM_NORTH_POLE_R1': 'Esker says the Attlerock\u2019s north pole (marked in red on my minimap) is a great spot to listen for the other travelers\u2019 music with a signalscope.',
    'TM_EYE_LOCATOR_R1': 'I hear there are Nomai ruins somewhere on the Attlerock. No one knows what they are or why they were built.',
    'TM_EYE_LOCATOR_R2': 'The Nomai text in the observatory talks about calibrating some sort of device on the Attlerock.',
    'TM_ESKER_X1': 'Esker is growing a crop of trees at their camp. They seemed to be doing ok, but they\u2019ve probably been alone on the moon for too long.',
    'TM_NORTH_POLE_X1': 'A lookout platform with a spectacular view of the solar system. Esker uses their signalscope here to keep tabs on the other travelers.',
    'TM_EYE_LOCATOR_X1': 'A Nomai device created to pinpoint the sources of distant signals.',
    'TM_EYE_LOCATOR_X2': 'The Nomai were disappointed by their failure to detect a signal from something called the Eye of the universe.',
    'TT_TIME_LOOP_DEVICE_R1': 'The central chamber inside Ash Twin was physically sealed off by an immensely thick protective shell.',
    'TT_TIME_LOOP_DEVICE_R2': 'The Nomai planned to construct technology capable of producing a 22-minute negative time interval on Ash Twin.',
    'TT_TIME_LOOP_DEVICE_R3': 'Every memory recorded by a Nomai statue is transmitted to a corresponding storage unit within Ash Twin.',
    'TT_TIME_LOOP_DEVICE_R4': 'An advanced warp core was approved for installation in the central chamber of Ash Twin.',
    'TT_WARP_TOWERS_X1': "Several large Nomai towers form a ring around Ash Twin's equator.",
    'TT_WARP_TOWERS_X2': 'The White Hole Station was used as a model for these towers, which were built for the Ash Twin Project.',
    'TT_TIME_LOOP_DEVICE_X1': 'A hollowed-out chamber inside Ash Twin. The energy cables from the surface are plugged into a protective casing at the center of the planet.',
    'TT_TIME_LOOP_DEVICE_X2': "There are eight monoliths with Nomai masks attached. Three of the masks are actively receiving data from the Probe Tracking Module, Giant's Deep, and Timber Hearth respectively.",
    'TT_TIME_LOOP_DEVICE_X3': 'The Ash Twin Project was designed to use the energy from a supernova (triggered by the Sun Station) to send probe data from the Orbital Probe Cannon 22 minutes into the past.',
    'TT_TIME_LOOP_DEVICE_X4': 'The Sun Station did not work. Although the Ash Twin Project was theoretically sound, the Nomai were unable to power it.',
    'TT_TIME_LOOP_DEVICE_X5': 'There is an advanced warp core inside the protective casing at the center of the planet. Removing the core will disable the Ash Twin Project.',
    'COMET_INTERIOR_R1': "The shuttle's equipment heard strange energy readings coming from somewhere beneath the surface.",
    'COMET_INTERIOR_R2': 'Two of the Nomai located a fissure in the ice on the Interloper\u2019s sunward side. They descended inside to investigate.',
    'COMET_SHUTTLE_X1': 'I found a Nomai shuttle almost completely encased in ice.',
    'COMET_SHUTTLE_X2': "The Nomai landed on the Interloper not long after its arrival in the solar system. The shuttle's equipment heard strange energy readings coming from somewhere beneath the surface.",
    'COMET_SHUTTLE_X3': 'There were three Nomai aboard the shuttle. One of them stayed behind to keep the shuttle warm while the other two explored the Interloper.',
    'COMET_SHUTTLE_X4': "Clary, the Nomai who stayed behind, lost contact with the other two after they descended below the Interloper's surface.",
    'COMET_INTERIOR_X1': 'I found the two missing members of the Nomai shuttle crew near a large ruptured stone that looks like it exploded from the inside.',
    'COMET_INTERIOR_X2': 'The Nomai traced the strange energy readings to a spherical stone casing filled with some form of exotic matter.',
    'COMET_INTERIOR_X3': 'They determined the exotic matter was both lethal and under extreme pressure. If the stone were to rupture, the exotic matter within would rapidly expand, completely blanketing the solar system almost instantaneously.',
    'COMET_INTERIOR_X4': 'One of the Nomai stayed behind to examine the alien matter while the other rushed back to the surface to warn the rest of the Nomai.',
    'QUANTUM_MOON_R1': 'The Nomai on Brittle Hollow observed a phantom moon that would sometimes appear in the sky.',
    'QUANTUM_MOON_R2': 'The Nomai on Ember Twin observed a moon that would disappear when no one was watching.',
    'QUANTUM_MOON_R3': 'A Nomai named Solanum landed a shuttle on the Quantum Moon.',
    'QUANTUM_MOON_R4': 'Chert\u2019s research notes mention a Quantum Moon that no Hearthian has been able to land on.',
    'QM_SHRINE_R1': 'The Nomai built a shrine on the Quantum Moon to aid in the pilgrimage to its sixth location.',
    'QM_SIXTH_LOCATION_R1': 'The Quantum Moon sometimes disappears, possibly to an unknown sixth location.',
    'QM_SIXTH_LOCATION_R2': 'Many Nomai went on a pilgrimage during which the Quantum Moon carried them to its sixth and most secret location.',
    'QM_SIXTH_LOCATION_R3': 'To explore the sixth location, the shrine on the Quantum Moon must be on the moon\u2019s north pole.',
    'QUANTUM_MOON_X1': 'I was able to land on the surface of the Quantum Moon.',
    'QUANTUM_MOON_X2': 'I found a dead Nomai in a space suit near the south pole.',
    'QM_SHUTTLE_X1': "A Nomai named Solanum landed her shuttle at the Quantum Moon's south pole and prepared to make the rest of the journey on foot.",
    'QM_SHUTTLE_X2': 'Visitors to the Quantum Moon always arrive at the south pole (for reasons unknown to the Nomai).',
    'QM_SHRINE_X1': 'A Nomai shrine that wanders about the Quantum Moon.',
    'QM_SHRINE_X2': '"You have recalled the rule of quantum imaging" is inscribed next to a mural of a tower on an island.',
    'QM_SHRINE_X3': '"Recall the rule of quantum entanglement" is inscribed next to a mural of a quantum shard in a cave.',
    'QM_SHRINE_X4': '"Recall the rule of the sixth location" is inscribed next to a mural of a tower hanging above a black hole.',
    'QM_SIXTH_LOCATION_X1': 'I met a living Nomai named Solanum at the south pole!',
    'QM_SIXTH_LOCATION_X3': "The Quantum Moon is the Eye of the universe's moon.",
    'QM_SIXTH_LOCATION_X5': 'At this location, the Quantum Moon becomes a reflection of the Eye itself.',
    'QM_SIXTH_LOCATION_X4': 'The Eye is likely the source of all macroscopic quantum phenomena in the solar system.',
    'QM_SIXTH_LOCATION_X2': 'Solanum wonders what would happen if a concious observer were to enter the Eye.',
    'QM_SIXTH_LOCATION_X6': 'Solanum has a hypothesis that she may not be entirely alive.',
    'IP_ZONE_1_SECRET_R1': 'A map I found in the Abandoned Temple reveals a secret location somewhere within the Stranger.',
    'IP_ZONE_2_SECRET_R1': 'A map I found in the Abandoned Temple reveals a secret location somewhere within the Stranger.',
    'IP_ZONE_2_LIGHTHOUSE_R1': 'I found a projection that reveals a cave entrance at the base of a rocky island with a tall tower.',
    'IP_ZONE_2_CODE_R1': "The light coming out of the vault gave me a vision of climbing a spiral staircase to a room near the top of a tower. One of the Stranger's inhabitants pointed at a mural of an identical tower beneath a ringed planet, then picked up an artifact and carried it downstairs to a room with a green fire. Some time later, two of the lamps in the mural room turned off, plunging the mural into darkness and revealing a secret passage.",
    'IP_ZONE_2_CODE_R2': 'The passage lead to three wooden containers, each marked with a glowing vault seal.',
    'IP_ZONE_3_SECRET_R1': 'A map I found in the Abandoned Temple reveals a secret location somewhere within the Stranger.',
    'IP_ZONE_3_ENTRANCE_R1': 'I found a slide reel in the Hidden Gorge that shows an explosion blowing a hole in the side of the Stranger.',
    'IP_ZONE_3_LAB_R1': 'I saw a building marked with a unique symbol recessed into one of the canyon walls, but the bridge that used to lead to it has rotted away.',
    'IP_PRISON_R1': 'According to a slide reel, a strange vault was encased in a large metal structure and lowered underwater.',
    'IP_PRISON_R2': 'I found a diagram of a hollow metal structure suspended by chains. There is a round hole underneath that appears to be the only entrance.',
    'IP_DREAM_LAKE_R1': 'I looked through a peephole in the side of a large metal structure suspended by chains. Inside is another green fire and a staircase leading farther below.',
    'IP_DREAM_LAKE_R2': 'I saw a vision-like recording of two figures taking artifacts into a large metal structure suspended by chains and going to sleep at the green fire in front of the sealed vault. Upon waking up with lit artifacts, the two figures picked up the vault and carried it down a staircase to somewhere farther below.',
    'IP_SARCOPHAGUS_R4': 'I found a strange vault wrapped in chains and marked with three glowing symbols.',
    'IP_SARCOPHAGUS_R1': 'A slide reel from the River Lowlands showed a strange vault being closed and sealed with chains and a glowing symbol.',
    'IP_SARCOPHAGUS_R2': 'A slide reel from the Cinder Isles showed a glowing symbol and chains appear around a strange vault.',
    'IP_SARCOPHAGUS_R3': 'A slide reel from the Hidden Gorge showed a glowing symbol and chains appear around a strange vault.',
    'IP_DREAM_ZONE_1_R1': 'I rode a raft through a densely wooded stretch of river. I can see buildings along the banks of the river.',
    'IP_DREAM_LIBRARY_1_R1': 'I found a hidden slide reel that shows a container marked with a glowing symbol being handed to a shadowy figure. The figure follows a procession of lights through a forest to a candlelit building, where they carry the container into a secret passage behind a roaring fireplace.',
    'IP_DREAM_ZONE_2_R1': 'I rode a raft past an island with a tall candlelit tower.',
    'IP_DREAM_LIBRARY_2_R1': 'The reel I found in the slide burning room shows a container marked with a glowing symbol being handed to a shadowy figure. The lights are extinguished, and the figure carries the container down into a dark well.',
    'IP_DREAM_ZONE_3_R1': 'I rode a raft through the bottom of a massive canyon. It looks like there are buildings set into the cliff face high above.',
    'IP_DREAM_LIBRARY_3_R1': 'The reel I found in the slide burning room shows a container marked with a glowing symbol being handed to a shadowy figure. The lights are extinguished, and the figure carries the container into a secret passage behind a mural of a large tree.',
    'IP_RING_WORLD_X1': 'A massive artificial ring world hidden within some sort of cloaking field. It does not appear to be Hearthian or Nomaian in origin.',
    'IP_ZONE_1_X1': 'A low-lying region near the entrance to the Stranger. There are wooden buildings along the banks of the river.',
    'IP_ZONE_1_X2': 'I found several ornate metal artifacts inside a workshop surrounded by ghost matter.',
    'IP_ZONE_1_STORY_X1': 'A slide reel that shows the origin of the Stranger and its inhabitants.',
    'IP_ZONE_1_STORY_X2': 'Several slides have been burned and cannot be viewed.',
    'IP_ZONE_1_SECRET_X2': 'A room full of burned slide reels piled next to a strange device.',
    'IP_ZONE_1_SECRET_X1': 'I found a hidden slide reel that shows a container marked with a glowing symbol being handed to a shadowy figure. The figure follows a procession of green lights through a forest to a candlelit building, where they carry the container into a secret passage behind a roaring fireplace.',
    'IP_ZONE_2_X1': 'A pair of small rocky islands connected by a village of stilt houses.',
    'IP_ZONE_2_X2': 'I found a large metal symbol inside a burned-out building that closely resembles the Nomai symbol for the Eye of the universe.',
    'IP_ZONE_2_STORY_X1': "A slide reel that shows the Stranger's inhabitants analyzing an anomaly that closely resembles the Nomai symbol for the Eye of the universe.",
    'IP_ZONE_2_STORY_X2': 'Several slides have been burned and cannot be viewed.',
    'IP_ZONE_2_SECRET_X2': 'A room full of burned slide reels piled next to a strange device.',
    'IP_ZONE_2_SECRET_X1': 'I found a hidden slide reel that shows a container marked with a glowing symbol being handed to a shadowy figure. The lights are extinguished, and the figure carries the container down into a dark well.',
    'IP_ZONE_2_LIGHTHOUSE_X2': 'A tower that sits atop one of the Cinder Isles. The upper floors can only be reached from a second entrance at the back of the tower.',
    'IP_ZONE_2_LIGHTHOUSE_X1': "I found a slide reel that shows the Stranger's inhabitants opening a secret passage in a round room filled with lanterns and murals. The inhabitants are shown filing into three of these rooms throughout the Stranger.",
    'IP_ZONE_2_CODE_X1': 'A secret room filled with wooden containers marked with different symbols.',
    'IP_ZONE_2_CODE_X2': 'Three of the containers are marked with glowing vault seals, but their contents have been burned away.',
    'IP_ZONE_2_CODE_X3': 'I opened the container marked with the symbol of a burning slide reel and found a vertical sequence of symbols inside.',
    'IP_ZONE_3_X1': 'A narrow gorge along the rightmost branch of the river. There are dwellings built into both cliff faces high above.',
    'IP_ZONE_3_SECRET_X2': 'A room full of burned slide reels piled next to a strange device.',
    'IP_ZONE_3_SECRET_X1': 'I found a hidden slide reel that shows a container marked with a glowing symbol being handed to a shadowy figure. The lights are extinguished, and the figure carries the container into a secret passage behind a mural of a large tree.',
    'IP_ZONE_3_STORY_X1': "A slide reel that shows the Stranger's inhabitants congregating around a strange green fire.",
    'IP_ZONE_3_STORY_X2': 'Several slides have been burned and cannot be viewed.',
    'IP_ZONE_3_ENTRANCE_X1': 'A laboratory with three test chambers. The second chamber is badly damaged and can be entered through a hull breach in the side of the Stranger.',
    'IP_ZONE_3_ENTRANCE_X2': 'I saw a vision-like recording of someone picking up an artifact and going to sleep in front of a green fire. The rest of the vision was distorted and difficult to make out, but a flame seemed to appear inside the artifact.',
    'IP_ZONE_3_ENTRANCE_X3': 'I found a slide reel that shows three experiments conducted with three different artifacts. The third experiment appears to have been a success.',
    'IP_ZONE_3_LAB_X1': 'An abandoned temple marked with the symbol of a burning slide reel. It can be accessed from a passage in the Hidden Gorge.',
    'IP_ZONE_3_LAB_X3': 'There is an interface upstairs that can be used to line up symbols in a vertical sequence.',
    'IP_ZONE_3_LAB_X4': 'Entering the correct sequence opens the path to a secret room beneath the temple.',
    'IP_ZONE_3_LAB_X2': "I found a slide reel that shows the Stranger's inhabitants removing all of the slide reels from their shelves, scanning each reel with a device, and incinerating specific slides as well as entire reels.",
    'IP_MAP_PROJECTION_1_X1': 'A projection that seems to reveal a secret location somewhere within the Stranger.',
    'IP_MAP_PROJECTION_2_X1': 'A projection that seems to reveal a secret location somewhere within the Stranger.',
    'IP_MAP_PROJECTION_3_X1': 'A projection that seems to reveal a secret location somewhere within the Stranger.',
    'IP_ZONE_4_X2': 'An enormous reservoir with wooden piers and buildings on both shores.',
    'IP_ZONE_4_X3': 'I found a room with a burned control interface and a projection that seems to indicate a broken connection between the Stranger and another craft.',
    'IP_ZONE_4_X4': "I found a projection showing the Stranger's current trajectory and the sun's predicted supernova radius.",
    'IP_ZONE_4_STORY_X1': 'A slide reel that shows a strange vault being encased in a large metal structure and lowered underwater.',
    'IP_ZONE_4_STORY_X2': 'Nearly all of the slides have been burned and cannot be viewed.',
    'IP_PRISON_X1': 'A large metal structure suspended by chains. It can be entered by swimming from below.',
    'IP_PRISON_X2': 'There is a sealed vault illuminated by a green fire inside the structure.',
    'IP_DREAM_LAKE_X1': 'I discovered a vast subterranean lake beneath the submerged structure. The sealed vault is resting on the shore of the lake. There are three interfaces, each marked with one of the three symbols from the vault.',
    'IP_DREAM_LAKE_X2': 'I rotated the mechanism in front of the vault, causing it to strain against the chains holding it shut. Moments later rays of green light spilled out of the vault.',
    'IP_SARCOPHAGUS_X2': "I met one of the Stranger's inhabitants who was imprisoned within the vault!",
    'IP_SARCOPHAGUS_X3': 'The Prisoner showed me a vision revealing the actions they took that resulted in their eternal confinement.',
    'IP_SARCOPHAGUS_X4': "I used the vision torch to share my knowledge of the solar system's history with the Prisoner.",
    'IP_SARCOPHAGUS_X5': "The Prisoner left one final vision for me by the water's edge as a farewell.",
    'IP_DREAM_ZONE_1_X1': 'A dense forest along the banks of a river.',
    'IP_DREAM_ZONE_1_X2': 'I heard music coming from a candlelit building across the water.',
    'IP_DREAM_ZONE_1_X3': 'I found a covered bridge leading into the darkest part of the forest.',
    'IP_DREAM_LIBRARY_1_X1': 'A library full of intact slide reels hidden deep underground.',
    'IP_DREAM_LIBRARY_1_X2': 'There is a container marked with one of the vault seals, but its contents have been destroyed.',
    'IP_DREAM_1_STORY_X1': 'I found a slide reel that shows the origin of the Stranger and its inhabitants.',
    'IP_DREAM_1_STORY_X2': 'Intact slides reveal the sacrifice that was made to build the Stranger.',
    'IP_DREAM_1_RULE_X1': "I found a slide reel that appears to be some sort of error report. It shows one of the Stranger's inhabitants jumping off a raft during a transition between areas and falling below the world.",
    'IP_DREAM_ZONE_2_X1': 'A secluded village nestled within a cove. A candlelit tower sits atop a nearby island.',
    'IP_DREAM_ZONE_2_X2': 'The well at the bottom of the village is guarded by a statue that activates an alarm bell when it sees me.',
    'IP_DREAM_ZONE_2_X3': 'I found the remains of a burned-out building on the outskirts of the village.',
    'IP_DREAM_ZONE_2_X4': "I reached the tower's upper floors by projecting a path to a second entrance at the back of the tower.",
    'IP_DREAM_LIBRARY_2_X1': 'A library full of intact slide reels hidden deep underground.',
    'IP_DREAM_LIBRARY_2_X2': 'There is a container marked with one of the vault seals, but its contents have been destroyed.',
    'IP_DREAM_2_STORY_X1': "I found a slide reel that shows the Stranger's inhabitants analyzing an anomaly that closely resembles the Nomai symbol for the Eye of the universe.",
    'IP_DREAM_2_STORY_X2': "Intact slides reveal the construction and launch of a spacecraft designed to block the Eye's signal.",
    'IP_DREAM_2_RULE_X1': 'I found a slide reel that shows two artifacts being lit near a green fire. The first artifact lights after its bearer falls asleep, and the second artifact lights after its bearer dies.',
    'IP_DREAM_2_RULE_X2': "I found a slide reel that appears to be some sort of error report. It shows an alarm bell failing to wake up one of the Stranger's inhabitants.",
    'IP_DREAM_ZONE_3_X1': 'A massive canyon that stretches into the distance. A candlelit lodge is built into the far cliff face.',
    'IP_DREAM_ZONE_3_X2': 'I found a mural of a large tree on the bottom floor of the lodge.',
    'IP_DREAM_LIBRARY_3_X1': 'A library full of intact slide reels hidden deep underground.',
    'IP_DREAM_LIBRARY_3_X2': 'There is a container marked with one of the vault seals, but its contents have been destroyed.',
    'IP_DREAM_3_STORY_X1': "I found a slide reel that shows the Stranger's inhabitants congregating around a strange green fire.",
    'IP_DREAM_3_STORY_X2': 'Intact slides reveal the creation of a simulated reality modeled after their home moon.',
    'IP_DREAM_3_RULE_X1': "I found a slide reel that appears to be some sort of error report. It shows one of the Stranger's inhabitants dropping their artifact on the ground and walking beyond its projection radius.",
    'GD_OCEAN_R1': 'Gabbro says there\u2019s a strong current beneath the surface of the ocean that prevents anything from sinking below it.',
    'GD_OCEAN_R2': "The Nomai on the Construction Yard saw something sink beneath the underwater current, which they'd previously thought was impossible.",
    'GD_OCEAN_R3': 'Feldspar found a way to reach the core of Giant\u2019s Deep.',
    'GD_GABBRO_ISLAND_R1': 'Hal says Gabbro went back to Giant\u2019s Deep to try to learn more about the Nomai statue in the observatory.',
    'GD_CONSTRUCTION_YARD_R1': 'The Nomai built the Orbital Probe Cannon at a Construction Yard on Giant\u2019s Deep.',
    'GD_STATUE_ISLAND_R1': 'One of the islands on Giant\u2019s Deep has a Nomai statue on the beach just like the one Gabbro brought back to Timber Hearth.',
    'GD_STATUE_ISLAND_R2': 'Statue Island (as Gabbro calls it) is the one with two islands connected by a natural rock arch.',
    'GD_STATUE_WORKSHOP_R1': 'I found a sign for a "Statue Workshop" next to a broken door that used to lead inside the island.',
    'GD_STATUE_WORKSHOP_R2': "Some Nomai children debated bypassing the Statue Workshop's door and sneaking inside via an alternate (more dangerous) route.",
    'GD_STATUE_WORKSHOP_R3': 'I can see into a large cave from one of the ruins on top of the island. The bottom of the cave is filled with water.',
    'GD_QUANTUM_TOWER_R1': 'The Nomai detected a Quantum signal coming from somewhere on Giant\u2019s Deep.',
    'GD_OCEAN_X1': "The ocean is surprisingly calm beneath the current. Some sort of electrical field surrounds the planet's core.",
    'GD_OCEAN_X2': "I passed through the electric barrier and reached the coral forest at the planet's core.",
    'GD_GABBRO_ISLAND_X0': 'Gabbro is lounging in a hammock near the island\u2019s shore.',
    'GD_GABBRO_ISLAND_X1': "Gabbro found a Nomai statue on another island. The statue's eyes started glowing and Gabbro saw their memories flash before their eyes.",
    'GD_GABBRO_ISLAND_X2': 'Gabbro remembers dying. They saw their memories flash before their eyes, just like the time with the statue.',
    'GD_GABBRO_ISLAND_X3': "Gabbro and I seem to be the only ones aware that we're in a time loop.",
    'GD_CONSTRUCTION_YARD_X1': 'This island is where the Nomai built the Orbital Probe Cannon.',
    'GD_CONSTRUCTION_YARD_X2': 'For some reason, the Nomai put the Orbital Probe Cannon on indefinite hiatus. The cannon was not asked to fire.',
    'GD_CONSTRUCTION_YARD_X3': 'According to a Nomai computer, a long-range probe was recently launched from the Orbital Probe Cannon.',
    'GD_BRAMBLE_ISLAND_X1': 'An island of thorny vines and what appears to be a frozen jellyfish. It looks like Feldspar camped here before heading off to Dark Bramble.',
    'GD_STATUE_ISLAND_X1': 'This island must be where the Nomai created statues like the one in our observatory.',
    'GD_STATUE_ISLAND_X2': 'I found a Nomai statue lying on the beach. It looks just like the one in our observatory.',
    'GD_STATUE_WORKSHOP_X1': 'Nomai statues were designed to pair with a single user, record their memories, and send those memories to a storage unit within the Ash Twin Project.',
    'GD_STATUE_WORKSHOP_X2': 'Each storage unit inside the Ash Twin Project was equipped with a mask (the statue\u2019s counterpart), which could then send those stored memories back to the corresponding user.',
    'GD_STATUE_WORKSHOP_X3': 'The statues were designed to only activate once the Ash Twin Project succeeded, or in the event that it failed.',
    'GD_QUANTUM_TOWER_X1': 'This tower held knowledge a Nomai needed to make his or her first quantum journey.',
    'GD_QUANTUM_TOWER_X2': '"Observing a quantum object; observing an image of a quantum object. These are the same."',
    'GD_QUANTUM_TOWER_X3': 'The Nomai called this the "Rule of Quantum Imaging."',
    'GD_QUANTUM_TOWER_X4': '"Remember, the other quantum shards have other lessons to teach."',
}

persistent_conditions = [
    'AUTOPILOT_INTO_SUN',
    'AskedGabbroAboutRadioTower',
    'AskedGabbroForHisShip',
    'COMPLETED_SHIPLOG_TUTORIAL',
    'ChertFirstContact',
    'DESTROYED_TIMELINE_LAST_SAVE',
    'FLEW_TO_SS',
    'FoundMapSatellite',
    'FromGiantsDeep',
    'GABBRO_MERGE_TRIGGERED',
    'GAME_OVER_LAST_SAVE',
    'HAS_AIMED_TRANSLATOR',
    'HAS_COMPLETED_DREAM_ZONE_2',
    'HAS_CONCEALED_FROM_GHOSTS',
    'HAS_CONCEALED_IN_DREAM',
    'HAS_DOZED_INTO_DREAM_WORLD',
    'HAS_FOCUSED_IN_DREAM',
    'HAS_PLAYER_LOCKED_ON',
    'HAS_PLAYER_LOCKED_ON_MAP',
    'HAS_RETRIEVED_PROBE',
    'HAS_ROTATED_PROBE_CAMERA',
    'HAS_SEEN_SUN_EXPLODE',
    'HAS_TAKEN_HANDHELD_SNAPSHOT',
    'HAS_TAKEN_MIDAIR_SNAPSHOT',
    'HAS_USED_JETPACK',
    'HAS_USED_MAP_SHIP',
    'HAS_USED_MAP_SUIT',
    'HAS_USED_PREFLIGHT_CHECKLIST',
    'HAS_USED_SHIPLOG',
    'HAS_USED_SLIDE_PROJECTOR',
    'HAS_USED_TRANSLATOR',
    'HIDE_TEMPLE_BASEMENT_ENTRIES',
    'KILLED_BY_SUPERNOVA_AND_KNOWS_IT',
    'KILLED_IN_GHOST_MATTER',
    'KNOWS_MEDITATION',
    'LAUNCH_CODES_GIVEN',
    'MARK_ON_HUD_TUTORIAL_COMPLETE',
    'MET_PRISONER',
    'MET_RIEBECK',
    'MET_SOLANUM',
    'MetFeldspar',
    'MetGabbro_Loop1',
    'PLAYER_ENTERED_TIMELOOPCORE',
    'PLAYER_ENTERED_TIMELOOPCORE_MULTIPLE',
    'PREFLIGHT_CHECKLIST_UNLOCKED',
    'PROBE_ENTERED_TIMELOOPCORE',
    'SUIT_BOOSTER_FIRED',
    'SayHiToEsker',
    'TALKED_TO_GABBRO',
    'THERE_IS_BUT_VOID',
    'TM_MOON_CRATER_X1',
    'ToldGabbroAboutHisShip',
    'TuffTooSick',
]

ephemeral_conditions_code = [
    'AllTravelersGathered',
    'AnyTravelersGathered',
    'BeginHideAndSeek',
    'BrokeMapSatellite',
    'CrashedModelRocket',
    'DB_VESSEL_X1',
    'EndHideAndSeek',
    'EnteredIP',
    'IP_RING_WORLD_X1',
    'JamSessionIsOver',
    'LOOP_COUNT_EQ_1',
    'LOOP_COUNT_EQ_2',
    'LOOP_COUNT_EQ_3',
    'LOOP_COUNT_GOE_1',
    'LOOP_COUNT_GOE_2',
    'LOOP_COUNT_GOE_3',
    'LOOP_COUNT_LOE_2',
    'LandedModelRocket',
    'LastKidToFind',
    'MAP_PROMPT_ATTENTION',
    'MAP_PROMPT_REMINDER',
    'PLAYER_TIMECLONE_FREAKOUT',
    'PROBE_ENTERED_EYE',
    'ParadoxLoopGOE2',
    'PostZeroG',
    'SCIENTIST_3',
    'SHOW_SIGNALSCOPE_PROMPT',
    'SLATE_SHIPLOG_TUTORIAL_PREREQ',
    'Space',
    'YesPicture',
]

ephemeral_conditions_dialogue = [
    'Arkose_loves_ghost_matter',
    'BeginHideAndSeek',
    'BeginMeditation',
    'ChertBreakdownNomai',
    'CoachSaysHi_1',
    'CoachSaysHi_2',
    'EndHideAndSeek',
    'EskerSaysHi',
    'FoundFeldsparsJournal',
    'FoundKidOne',
    'FoundKidTwo',
    'FriendSaysHi',
    'FriendSaysHiAgain',
    'HasTalkedtoMoraine',
    'HornfelsStatueEyes',
    'MAP_PROMPT_ATTENTION',
    'MAP_PROMPT_REMINDER',
    'METCHERT_1',
    'MayorSaysHi',
    'PorphySaysHi',
    'SCIENTIST_1',
    'SHOW_SIGNALSCOPE_PROMPT',
    'SaidHiToChert',
    'SaidHiToChert2',
    'SaidHiToChert3',
    'SaidHiToGabbro',
    'SaidHiToSpinel',
    'ScaredMinerSecondary',
    'Secondary1',
    'Secondary2',
    'ShyKidFirstContact',
    'ShyKidSaysHi',
    'SpinelGrumpy',
    'TalkToRiebeck',
    'TalkedToFeldspar',
    'TalkedToGneiss',
    'TalkedToHornfels',
    'TalkedToImpactTektite',
    'TalkedToTuff',
    'TalkedToWeirdKid',
    'ToldGabbroAboutHisShipThisLoop',
    'TooSick',
    'Tree',
]
